name: vscode extension ci

on:
    push:
      branches: [ "master" ]
    pull_request:
      branches:
        - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 21.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        npx tsc
    - name: Install VSCE
      run: npm install -g vsce
    - name: Build VSIX
      run: vsce package