name: release extension

on:
    push:
      tags:
        - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 21.x

    - name: Build
      run: |
        npm install
        npx tsc
    - name: Install VSCE
      run: npm install -g vsce
    - name: Build VSIX
      run: vsce package
    - name: GitHub Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ./*.vsix
        prerelease: true